feat: useToggle 생성

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+echo "============================"
+echo "Running lint checks before commit..."
+echo "============================"
+
 npx lint-staged
+
+if [ $? -ne 0 ]; then
+  echo "❌ Lint failed! Please fix the errors before committing."
+  exit 1
+fi
+
+echo "✅ Lint passed! You can commit now."
